---
title: "Bobcat Life Table"
author: "Nikole Vannest, Teague Tran, Alyssa Kibbe"
date: "2/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(here)
library(kableExtra)
library(ggplot2)

options(scipen=999)  # Disable Scientific Notation
```

## Start adding life table data here

```{r read in data}
bobcat_data <- read.csv(here("data", "bobcats_lifetable.csv"), header = T)
```

```{r convert to survivorship}
# create empty list
surv_data <- c()

# fill list with survival proportions via loop
for(i in 1:nrow(bobcat_data)){
  surv_data[i] <- bobcat_data$Counts[i]/bobcat_data$Counts[1]
}

# Add to bobcat_data data frame
bobcat_data$survival <- surv_data
colnames(bobcat_data) <- c("age", 
                           "mx",
                           "count",
                           "survival")
```

```{r fit survival to curve}
# smooth survival data as curve

ggplot(data = bobcat_data,
       aes(x = age,
       y = survival))+
  geom_point()

plot(bobcat_data$age, bobcat_data$survival,
     main="Bobcat Survival Analysis",
     xlab = "Age (years)",
     ylab = "Survival (proportion)")

#making the best fit line from our data
line_fit = lm(log(bobcat_data$survival)~ #only take the log(y)
                bobcat_data$age)
summary(line_fit)

factor = line_fit$coefficients["bobcat_data$age"]
coeff = exp(line_fit$coefficients["(Intercept)"])

fit_eq = paste("y=",coeff, "exp(",factor,"x)")
#text(20,10,fit_eq)
#adds to the plot above
#create function called survivorship
survivorship <- function(x){
  coeff*exp(factor*x)
}
#add to plot above
curve(survivorship,0,14, add = TRUE, col="blue")
```

### Create list of survival data points to sample from
```{r}
# loop through survival to make list of potential points

# Remove the first row
bobcat_survival <- bobcat_data[-1,]

# Create list to loop into
list_survival <- list()

# Use loop to create list of lists containing potential survival data from age a to b
for(i in 1:12){
a <- seq(from = bobcat_data$survival[i], to = bobcat_data$survival[i+1], by = -0.001)
list_survival[[i]] <- a
}
```

### Placeholder for future data
```{r Life Table Data}
# Create multiple life tables with sampled survival data
survival_sampled <- list()
for(a in 1:12){
  for(i in length(list_survival[[a]])){
    survival_sampled[[a]] <- sample(list_survival[[a]], size = 5, replace = T)
  }
}

# Needs to be fixed from here down #########################
# Find a way to loop the new survival data into life tables
life_table <- array(data = NA, dim = c(12, 7, 5))
temp <- c()
for(a in 1:12){
  for(b in 1:100){
    temp[a] <- survival_sampled[[a]][b]*bobcat_survival$mx[a]
    life_table[,a,b] <- temp
  }
}

############# from class ########################3
life_table <- bobcat_data %>%
  mutate("lx*mx" = lx*mx, # Survivorship * fecundity -> Used to calculate (R0)
         "x*lx*mx"=age*lx*mx, # Used to calculate (G)
         "Lx"=(lx+lead(lx))/2, # Avg survivorship
         "Lx"=replace(Lx, 14, 0),   # change to 30 for oldest age class
         "ex"=rev(cumsum(rev(Lx)))/lx, # Used to calculate growth rate (r)
         "R0"=sum(lx*mx),# Net Reproductive Rate
         "G"=sum(age*lx*mx)/R0, # Generation time
         "approx.r"=log(R0)/G #approximating growth rate
  )

#life_table #check your work

# Use approximated growth rate to find actual growth rate
df <- as.data.frame(life_table)
r <- mean(df$approx.r) #approximated growth rate from df
x <- sum(exp(-r*df$Age)*df$`lx*mx`) # 
while (abs(x-1) >= 0.000001) {
  if (x-1>0){
    r <- r+0.00000001
  }
  else{
    r <- r-0.00000001
  }
  x <- sum(exp(-r*df$Age)*df$`lx*mx`)
  r
}

#use r to fill out the remainder of the life table
life_table <- life_table %>%
  mutate(
    "approx.r" = log(R0)/G, 
    "r" = r,
    "Vx" = rev(cumsum(rev(exp(-r*Age)*lx*mx)))/exp(-r*Age)*lx, #Reproductive value
    "lx*mx*e^-rx" = lx*mx*exp(-r*Age), # Used to get growth rate
    "approx.Vx" = rev(cumsum(rev(exp(-approx.r*Age)*lx*mx)))/exp(-approx.r*Age)*lx, # Approximate reproductive value from an approximated r value
    "approx.lx*mx*e^-rx" = lx*mx*exp(-approx.r*Age) # intermediate to get growth rate
  )

# as Yong Fu says, "Printing a pretty life table"!
kable(life_table, format="markdown", align="c", digits = 3)

# or just export it to a csv file
#write.csv(life_table,"bison_life_table.csv", row.names = FALSE)

# plot the data
life_table %>% ggplot(aes(x = Age)) +
  geom_line(aes(y = lx), size = 1) +
  ggtitle("Survivorship of Yellowstone NP Bison") +
  ylab("Survivorship") 
```
```{r}
#Teague's approach

# Use loop to create list of lists containing potential survival data from age a to b
for(i in 1:13){
a <- seq(from = bobcat_data$survival[i], to = bobcat_data$survival[i+1], by = -0.001)
list_survival[[i]] <- a
}

# Create multiple life tables with sampled survival data
survival_sampled <- list()
for(a in 1:13){
  for(i in length(list_survival[[a]])){
    survival_sampled[[a]] <- sample(list_survival[[a]], size = 5, replace = T)
  }
}

#create data frame for sampled survival data

survival_sampled_df <- data.frame(survival_sampled) 

#give it column names
colnames(survival_sampled_df) <- c("0_1",
                            "1_2", 
                           "2_3",
                           "3_4",
                           "4_5",
                           "5_6",
                           "6_7",
                           "7_8",
                           "8_9",
                           "9_10",
                           "10_11",
                           "11_12",
                           "12_13"
                           )
# transpose table so that it'll look like the bobcats dataframe
transposed_df<- t(survival_sampled_df)

#combine data column 
bobcat_lifetable <- cbind(bobcat_survival, transposed_df)

rlist <- list()

#create iteration to calculate r; we are only interested in the R values! 

for(i in 5:ncol(bobcat_lifetable)) { #code to iterate across columns; goes from fifth column until it finishes!
  lxmx <- bobcat_lifetable$mx* bobcat_lifetable[ , i] 
  R0 <- sum(lxmx)
  G <- sum(bobcat_lifetable$age*lxmx)/R0
  approx.r <- log(R0)/G
  r <- mean(approx.r) #approximated growth rate from df
  y <- sum(exp(-r*bobcat_lifetable$age)*lxmx) # 
  
while (abs(y-1) >= 0.000001) {
  if (y-1>0){
    r <- r+0.00000001
  }
  else{
    r <- r-0.00000001
  }
  y <- sum(exp(-r*bobcat_lifetable$age)*lxmx)
  r
}
  rlist <- append(rlist, r) #create a list of r values from the stuff; a range of these values will give you the good good
  
}


```


